### ISSUE TITLE
Adjust styling so that column headers are easier to view on weekly view

### ISSUE THREAD

**Issue by klbaker** [cse110-w21-group7/cse110-SP21-group7#237]
## Detailed Description

The weekly view is a page on our bullet journal that allows users to see daily-logs from the overview of the current week (from Monday to Sunday). For instance, if today is Thursday, then all daily logs from Monday to Thursday will be displayed if they exist.
The current implementation lacks proper styling. In order to remedy this, we are primarily interested in completing the following changes:
* Make the font size for days larger
* The date should appear on the same line as the day (i.e. 'Monday 5/25')
* Ensure that all days appear on the same row (spacing on the left of the calendar is too large)
## Context
Each column of the weekly view has a header that should be easily identifiable. By making these changes to the styling, it will be easier for the user to navigate by promoting visual clarity. This can be benchmarked during QA with the blurry-eye test.
## Possible Implementation

For the weekly view, we are using a custom component titled `WeeklyViewItem.js`. Styling changes are likely to happen in the shadow DOM for these components.
## Your Environment

* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by NoahT** [comment]
@klbaker make sure you are using the issue template when creating new issues.
