### ISSUE TITLE
Navigation via books from Index Page

### ISSUE THREAD

**Issue by will-chung** [cse110-w21-group7/cse110-SP21-group7#238]
## Detailed Description
User should be able to navigate to specific daily logs via the Index Page by clicking on a book.

## Context
- Part of the core functionality of the Index Page to be able to navigate throughout the bullet journal.  
- Easy navigation from Index Page.

## Possible Implementation
- Similar to implementation for navigation from Collections page.
- Issue #241 includes the idea of using query parameters for navigation instead. For this issue, we plan to perform a similar implementation.

## Your Environment
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by NoahT** [comment]
@yuzilyu @will-chung and I are considering on including a class for routing called `utils/Router.js` that piggybacks off the idea of using query parameters to help with navigation. This class will include the following:
- Setting the link for navigation (query parameters, and base of the relative URL to use)
- Getting the query parameters from navigation (when we are on a new page, an easy way to get the query parameters).

This is more or less a wrapper using the classes from the [URL interface](https://developer.mozilla.org/en-US/docs/Web/API/URL). We wanted your feedback on this in case you already started refactoring the navigation

**Comment by yuzilyu** [comment]
Ig the only question I have is do we need a Router.js to achieve this functionality? I just set the href with the hash included in the url and it works from collection to collection-edit

**Comment by NoahT** [comment]
We don't need `Router.js` to achieve this functionality, but doing so decouples the work for routing. Since this class would be isolated, it makes it easier for other teammates to unit test
