### ISSUE TITLE
Add business/presentation logic for tags on `daily.html`

### ISSUE THREAD

**Issue by thanhtong010** [cse110-w21-group7/cse110-SP21-group7#239]
## Detailed Description

Users should be able to add tags to their daily logs corresponding to some collection. For this issue, we will look at what format we should have tags for the daily log (dropdown, user creates custom tags, etc).
## Context

We want the daily logs to be more customizable for users by including tags. This is a motivating factor for the concept of a bullet journal, which is to promote structure and organization for tasks, notes, and events on a daily basis. Adding tags gives users an additional outlet for organization.

## Possible Implementation

The business/presentation logic is somewhat dependent on a new iteration of the existing schema we are using for indexedDB; the existing schema does not include a section for collection tags for any entry in the field `$defs["daily-log"]`. To complete this task, we should first consider including a field labeled `collection-tags` for each daily log entry. This field is an array containing JSON objects of the following format:
```
{
  "description": "Arbitrary collection tag",
  "name": "Collection tag name"
}
```
From the newest iteration of our schema, the business logic will follow in the same fashion as issues such as #190.
## Your Environment

* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Desktop windows

**Comment by NoahT** [comment]
This issue is somewhat large for one person, so I am breaking it into two parts (reading the collections info from indexedDB, and showing the available collections on `daily.html` to the user)

**Comment by NoahT** [comment]
@will-chung already addressed this issue earlier in the sprint, so I am closing it for now.
