### ISSUE TITLE
Update database when updating or deleting collection tasks

### ISSUE THREAD

**Issue by alvinwang922** [cse110-w21-group7/cse110-SP21-group7#240]
## Detailed Description
From the high-fidelity wireframes for `collection-edit.html`, we have that each collection contains a section for tasks relevant to that collection. These tasks should have some form of data persistence, so that when a user completes/uncompletes a tasks, deletes a task, etc., this information is reflected to the user when collections are viewed at a later time.
## Context

For our minimum viable product, we wish that tasks for collections are completely functional. Consequently, this is a high priority issue.
## Possible Implementation

We already have existing examples setup with indexedDB for `colleciton-edit.js` and `daily.js`. In order to complete this task, example code can be viewed from both of these files for how we are interacting with indexedDB.
## Your Environment

* Browser Name and version:--
* Operating System and version (desktop or mobile):--

**Comment by NoahT** [comment]
@alvinwang922 when you create issues, you need to make them descriptive so we know what this issue entails (we also addressed this in standup).
I updated the issue to include an outline of what needs to be done, but next time use the issue template
