### ISSUE TITLE
Navigation from collection page to collection edit

### ISSUE THREAD

**Issue by yuzilyu** [cse110-w21-group7/cse110-SP21-group7#241]
Currently we need a navigation scheme to go from collection page to actually editing it
## Detailed Description
When click on the collection folder icon, the user should be taken to the edit page
## Possible Implementation
Use pushstate to help with keeping track of which collection number user is querying
## Your Environment

* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): PC Windows

**Comment by NoahT** [comment]
@yuzilyu should we update implementation to include URL encodings? We can also add that this is a better solution for navigation than what we had before with the field `current_log` and `current_collection` in our schema

**Comment by yuzilyu** [comment]
I will include an explanation in the pr that's linked to this if that's okay
