### ISSUE TITLE
Implement Business Logic Yesterday/Tomorrow buttons

### ISSUE THREAD

**Issue by brettherbst** [cse110-w21-group7/cse110-SP21-group7#256]
In daily.html, below the text box where the user can enter their logs, and above the mood slider, are 2 arrows that direct the user the yesterday and tomorrow's logs. This issue is concerning the implementation of the business logic of these buttons
## Detailed Description
When the user clicks on the left arrow, it will direct the user to the log for the day before the current log. If this logs exists, the daily.html will populate accordingly, and if it does not exist, will create a new blank log for that day. Same logic would apply to the right arrow, except would instead be the day after the current log.
## Context
This change is important because it allows the user to quickly access the logs around the current day's log, which allows for rapid logging for upcoming days.  
## Possible Implementation
Will add event listener for these buttons on click, will then populate daily.html when a click occurs, and create a new log if necessary
## Your Environment
* Browser Name and version: Chrome 90 on Windows 10
* Operating System and version (desktop or mobile): Desktop

**Comment by NoahT** [comment]
Nothing to add here, just wanted to say I appreciate the high quality, detailed issue you wrote.
