### ISSUE TITLE
Weekly page not displaying the correct date

### ISSUE THREAD

**Issue by yuzilyu** [cse110-w21-group7/cse110-SP21-group7#257]
I opened the app today, May 30th, Sunday, and the weekly page did not populate the correct week
## Detailed Description
The weekly page populated the week of 5.31 to 6.6
## Context
We need to look into the function and check if there is any places that were off by one
## Your Environment

* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by NoahT** [comment]
I was responsible for some of the changes that induced this bug (sorry about that); if needed let me know and we can do pair programming to resolve it

**Comment by yuzilyu** [comment]
thanks for letting me know, I'm working on it rn, i'll update you on the progress
