### ISSUE TITLE
Update the high-fidelity wireframes in order to include `search.html`

### ISSUE THREAD

**Issue by NoahT** [cse110-w21-group7/cse110-SP21-group7#288]
## Detailed Description
We are currently interested in implementing a new navigation point of our bullet journal `search.html`. This page allows users to perform search queries through their bullet journal with respect to entries in both daily logs and collections. The current iteration of our high-fidelity wireframes currently do not account for `search.html`, and should reflect these new changes.

## Context

As we reiterate over the design of our bullet journal, it is important for us to have a high degree of consistency with the high-fidelity wireframes that we agreed to during our design phase.

## Your Environment

* Browser Name and version:--
* Operating System and version (desktop or mobile):--

**Comment by NoahT** [comment]
@yuzilyu we may have discussed this in standup as already being done; should I mark this as a duplicate issue?

**Comment by yuzilyu** [comment]
Yeah go ahead
