### ISSUE TITLE
Fix the logic of the entry selection part on daily log page

### ISSUE THREAD

**Issue by fatIvan** [cse110-w21-group7/cse110-SP21-group7#295]
## Detailed Description
Fixed the buttons on the daily log page, as well as the order each input comes out.
## Context
The entry selection part now looks better and functions as we planned in the standup meeting.
## Possible Implementation
Modify the related Javascript, HTML, and CSS files.
## Your Environment

* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by yuzilyu** [comment]
I think the only logic that needs to fix is when task is selected, after the month, the time shouldn't show up. But for some reason it does, so we need to fix that

**Comment by NoahT** [comment]
Closing this issue, since it was likely mistaken for a pull request
