### ISSUE TITLE
Navigation from weekly view to daily log

### ISSUE THREAD

**Issue by yuzilyu** [cse110-w21-group7/cse110-SP21-group7#299]
**Describe the bug**
When I click on the column links in weekly view, I am taken to the daily log page. However, the daily log is not populated with the corresponding day.

**To Reproduce**
1. Index page, click on one of the active books 
2. Weekly page, click on the column link
3. See error

**Expected behavior**
The daily log should be populated 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NoahT** [comment]
@yuzilyu we resolved this yesterday on my fork correct?

**Comment by yuzilyu** [comment]
@NoahT I think so

**Comment by NoahT** [comment]
Resolved by #356.
