### ISSUE TITLE
Collection tag fix

### ISSUE THREAD

**Issue by will-chung** [cse110-w21-group7/cse110-SP21-group7#308]
Error with collection tag functionality.

## Detailed Description
User unable to add a daily log to a collection because no options appear.

## Context
Bug fix.

## Possible Implementation
Wrong call to callback method, add parameter.

## Your Environment
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by yuzilyu** [comment]
![image](https://user-images.githubusercontent.com/57729578/120740442-12916380-c4a8-11eb-8e1f-5ac48a50aeca.png)

**Comment by yuzilyu** [comment]
![image](https://user-images.githubusercontent.com/57729578/120740492-24730680-c4a8-11eb-850a-6bbaf82f84da.png)

**Comment by yuzilyu** [comment]
I did see it work during the demo, it's so weird that it doesnt work on my end

**Comment by yuzilyu** [comment]
Okay to reproduce this bug, delete the database first, reload data, go straight to daily log, then you will encounter this bug
