### ISSUE TITLE
Page loads infinitely if you refresh the page when media gallery is visible

### ISSUE THREAD

**Issue by alvinwang922** [cse110-w21-group7/cse110-SP21-group7#324]
**Describe the bug**
In collection-edit, when you click the dropdown to display images and videos but refresh the page without hiding the media, the webpage is stuck on "Fetching your data..." and loads forever.

**To Reproduce**
1. Go to the navigation bar on the left
2. Click on 'Collection'
3. Click on any of the collections
4. Click on the carrot icon under adding tasks to expand the media gallery
5. Refresh the page
6. Watch it be stuck on "Fetching your data..."

**Expected behavior**
After you reload the page with media visible, it should reload the page without getting stuck or fetching data forever and still have the media gallery expanded and visible.

**Screenshots**
<img width="711" alt="Screen Shot 2021-06-06 at 1 52 40 PM" src="https://user-images.githubusercontent.com/53798269/120940085-3cc56a00-c6d0-11eb-9b70-2ed7cc85ffc9.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NoahT** [comment]
@yuzilyu @will-chung  I'm having trouble reproducing this. Can you guys try it out for me?

**Comment by yuzilyu** [comment]
@NoahT I think I fixed it in one of the commits

**Comment by yuzilyu** [comment]
@NoahT I think before this only happens with empty collection. The logic in javascript was trying to fetch the videos when there isn't any so it will infinitely loads. But I added the logic for when there isn't any videos

**Comment by NoahT** [comment]
Okay, then let's close this issue
