### ISSUE TITLE
Collection add button overlaps with list of collections

### ISSUE THREAD

**Issue by alvinwang922** [cse110-w21-group7/cse110-SP21-group7#328]
**Describe the bug**
In the collections page, the button to add a new collection overlaps with the section with all the collections, even when page is opened in full screen.

**To Reproduce**
1. Go to the navigation bar on the left
2. Click on Collection
3. See overlap of button and section with collections

**Expected behavior**
It would probably be better to make sure the add button and the collection section don't overlap because when the collection section is fully populated, the add button may overlap with an actual collection.

**Screenshots**
<img width="1287" alt="Screen Shot 2021-06-06 at 1 51 03 PM" src="https://user-images.githubusercontent.com/53798269/120942778-ef50f900-c6df-11eb-8d22-aca9518ce5ea.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NoahT** [comment]
I don't believe this is a bug; we intended to include this behavior for the add button from our wireframes.
