### ISSUE TITLE
WeeklyViewItem sometimes show up sometimes doesn't

### ISSUE THREAD

**Issue by yuzilyu** [cse110-w21-group7/cse110-SP21-group7#330]
**Describe the bug**
When navigate from books to weekly view, the weeklyViewItem show up properly
When navigate directly to weekly view using nav bar, the weeklyViewItem doesn't show up
**To Reproduce**
1. Make a new daily log entry
2. go back to index page
3. click the weekly view from the nav bar
4. see bug
**Expected behavior**
Data persistence is broken here

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NoahT** [comment]
Resolved by #356.
