### ISSUE TITLE
Search not found prompt

### ISSUE THREAD

**Issue by yuzilyu** [cse110-w21-group7/cse110-SP21-group7#331]
**Describe the bug**
We need to prompt the user when there is no entries found, currently there is nothing

**Expected behavior**
We could just do an alert

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NoahT** [comment]
I think a graceful way to handle this is to quantify to the user how effective their search pattern was. For instance, if a search query does not result in any matches, we can display 'Search results: #entries', where #entries is the number of entries found

**Comment by yuzilyu** [comment]
That’s a great suggestion. We just have to make sure the number displayed should be the number of days, not how many events tasks etc found
