### ISSUE TITLE
Confusing time display in daily log

### ISSUE THREAD

**Issue by alvinwang922** [cse110-w21-group7/cse110-SP21-group7#345]
**Describe the bug**
When entering an event in daily logs, if you enter an event that starts at a full hour (xx:00), it will only display one digit after the colon. For example, an event for 12:00 just displays 0:0.

**To Reproduce**
1. Go to navigation bar on the left
2. Click on 'Daily Log'
2. Click on 'Event' under 'Entry type:'
3. Add an event that starts at a full hour (00 for the minutes) with any date and description and click 'Save'
4. See only one digit for the minute section of the event

**Expected behavior**
It may be confusing to users that this represents the time of the event if the time displays something like '0:0' or '1:0'. Ideally, even if an event starts at an exact hour, we want to display both zeros after the colon to make it clear that this is the time the event starts.

**Screenshots**
<img width="1047" alt="Screen Shot 2021-06-08 at 12 22 03 AM" src="https://user-images.githubusercontent.com/53798269/121142021-6d9cc080-c7f0-11eb-96ca-77583e2aad83.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thanhtong010** [comment]
To add onto this, we may want to change the time from military time to standard time like Jordan suggested so that it matches with what the user inputs for time in the daily log.
