### ISSUE TITLE
Search functionality has different results

### ISSUE THREAD

**Issue by thanhtong010** [cse110-w21-group7/cse110-SP21-group7#352]
**Describe the bug**
For the Search Feature, sometimes typing in a search will give me different results. For example, I have the log with the task "Walk dog" and event "COGS101A Midterm". When I type "Walk", it just gives me the result "Walk dog". However, when I type "dog", it has both "Walk dog" and "COGS101A Midterm" on the daily log result. There are also some issues where I type in keywords but the expected result does not show up. Will attach pictures below so it's easier to see.

**To Reproduce**
1. Go to current daily log.
2. Add a task and another event.
3. Go to the search bar.
4. Search for that tasks and/or event separate, using different keywords to search each time.
5. See error

**Expected behavior**
I'm not sure what the expected result is for the search feature (if it should only show the event/task/note w/ the keyword in the daily log or if it should show all the events/notes/tasks in the daily log, but will display the daily log(s) that have the keywords).

**Screenshots**
![image](https://user-images.githubusercontent.com/72485537/121242130-0e22cd00-c851-11eb-88f3-300ad734b38e.png)
<img width="960" alt="2021-06-07 (9)" src="https://user-images.githubusercontent.com/72485537/121241923-d1ef6c80-c850-11eb-98fb-50f7fd627a37.png">
<img width="960" alt="2021-06-07 (10)" src="https://user-images.githubusercontent.com/72485537/121241952-da47a780-c850-11eb-9da0-d4456fda9f42.png">
<img width="960" alt="2021-06-08" src="https://user-images.githubusercontent.com/72485537/121242221-285cab00-c851-11eb-8a4d-0596f5aed154.png">
<img width="960" alt="2021-06-08 (2)" src="https://user-images.githubusercontent.com/72485537/121242274-35799a00-c851-11eb-87a0-9c7162617db0.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thanhtong010** [comment]
Also, this is not a bug, but I noticed that when I click "enter" on the search entry, it does not actually search for the item (and just gives blank results). I have to click on the search button every time to search for something. Is there a way to search the item when the user hits "enter"?

**Comment by NoahT** [comment]
@thanhtong010 that's a great idea, but we decided to halt new features on Sunday of this week to focus on QA and bug fixes 😞
