### ISSUE TITLE
Can still toggle tasks on the weekly view

### ISSUE THREAD

**Issue by thanhtong010** [cse110-w21-group7/cse110-SP21-group7#353]
**Describe the bug**
On the weekly view, I can still toggle tasks from finished to unfinished and vice versa. However, this change does not save. (If I refresh the page, it will go back to the previous state). This could be confusing for users who find that they can toggle on the weekly view. 

**To Reproduce**
1. Go to Weekly Page.
2. Toggle a task on the weekly page.
3. See error

**Expected behavior**
The expected behavior should be that the user cannot toggle tasks at all on the weekly view.

**Screenshots**
<img width="960" alt="2021-06-08 (4)" src="https://user-images.githubusercontent.com/72485537/121243160-3fe86380-c852-11eb-997b-eadea2b80a34.png">
<img width="960" alt="2021-06-08 (5)" src="https://user-images.githubusercontent.com/72485537/121243166-41b22700-c852-11eb-89fd-e23ec3997473.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yuzilyu** [comment]
This is the same as #306
