### ISSUE TITLE
Change default text for notes/tasks/events in daily log

### ISSUE THREAD

**Issue by thanhtong010** [cse110-w21-group7/cse110-SP21-group7#354]
**Describe the bug**
This is not necessarily a bug but more so a change that would make more sense for the user. Currently, when the user makes a task/note/event/reflection for the daily log, the default text is always "Input your todo here". However, that does not make sense when the entry type is a reflection for example. It could be better if we customize them for reflection and event maybe (just simple fix to "Input your reflection here").

**To Reproduce**
1. Go to daily log entry.
2. Click on Reflection/Note/Event/Task
3. See the default text.

**Screenshots**
<img width="960" alt="2021-06-08 (6)" src="https://user-images.githubusercontent.com/72485537/121243942-272c7d80-c853-11eb-999a-710507eb0c1c.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NoahT** [comment]
Great catch, we'll assign someone to this today
